### ISSUE TITLE
Corrigir estilo pep8 no models.py & forms.py

### ISSUE THREAD

**Issue by HigorMonteiro** [teresinahc/savetheangico#1]
Organizar estilo pep8 em models.py

`from app import db`
`+`
`+`
`class Base(db.Model):`

**Comment by HigorMonteiro** [comment]
Organizar estilo pep8 em forms.py

segundo a padrão de estilo `PEP8` os `imports` listadas abaixo deveram ser retiradas 
pois os mesmos não estão sendo utilizados .

```
RecaptchaField
PasswordField
from app import db 
```

**Comment by renatoalencar** [comment]
Adicionado com o PR #2
